import { GetServerSideProps } from "next";
import Head from "next/head";
import { getCookie } from "cookies-next";

import api from "../lib/api";
import { User } from "../types";
import UserList from "../components/user-list";

interface Props {
  users: User[];
}

const Home = ({ users = [] }: Props) => {
  return (
    <div>
      <Head>
        <title>Bookpot Admin | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="h-full w-full flex flex-col gap-y-8">
        <div className="h-10 w-full flex items-center justify-between">
          <h1 className="text-2xl text-[#1C1C1C] font-bold">회원 관리</h1>
        </div>
        <div>
          <UserList users={users} />
        </div>
      </section>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const accessToken = getCookie("accessToken", { req, res });

  if (!accessToken) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  const response = await api.get("/api/v1/users", {
    headers: {
      Cookie: req.headers.cookie,
    },
  });

  return {
    props: {
      users: response.data,
    },
  };
};

export default Home;
